ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

COPY pyproject.toml style.css main.py /app/

RUN python -m pip install --no-cache-dir uv && \
    uv pip install --system --quiet . 

RUN chown -R appuser:appuser /app

USER appuser

CMD ["python", "main.py"]
