services:
  readme-to-pdf:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - OUTPUT_PDF=Taha_Abdelaziz_Sr_DevSecOps_Engineer.pdf
    volumes:
      - ./README.md:/app/README.md:ro
    working_dir: /app
