version: '3.8'

services:
  readme-to-pdf:
    build: .
    environment:
      - OUTPUT_PDF=Taha_Abdelaziz_Sr_DevSecOps_Engineer.pdf
    volumes:
      - ./README.md:/app/README.md:ro
    working_dir: /app
